package com.example.android.bakingapp.data;

import android.arch.persistence.room.ColumnInfo;
import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.PrimaryKey;
import android.arch.persistence.room.Room;
import android.arch.persistence.room.TypeConverters;

import com.example.android.bakingapp.model.Ingredient;
import com.example.android.bakingapp.model.Step;

import java.util.List;

/**
 * Defines the schema of a table in {@link Room} for a single recipe.
 */
@Entity(tableName = "recipe")
public class RecipeEntry {

    /**
     * Makes sure the id is the primary key (ensures uniqueness), is auto generated by {@link Room}
     */
    @PrimaryKey(autoGenerate = true)
    private int id;

    @ColumnInfo(name = "recipe_id")
    private int recipeId;

    private String name;

    @TypeConverters(IngredientsConverter.class)
    private List<Ingredient> ingredients;

    @TypeConverters(StepsConverter.class)
    private List<Step> steps;

    private int servings;

    private String image;

    /**
     * Constructor
     * @param recipeId Recipe ID
     * @param name Name of recipe
     * @param ingredients List of ingredients of the recipe
     * @param steps List of steps of the recipe
     * @param servings The number of servings
     * @param image Image URL
     */
    @Ignore
    public RecipeEntry(int recipeId, String name,
                       List<Ingredient> ingredients, List<Step> steps, int servings,
                       String image) {
        this.recipeId = recipeId;
        this.name = name;
        this.ingredients = ingredients;
        this.steps = steps;
        this.servings = servings;
        this.image = image;
    }

    /**
     * Constructor used by Room to create RecipeEntries
     */
    public RecipeEntry(int id, int recipeId, String name,
                       List<Ingredient> ingredients, List<Step> steps, int servings,
                       String image) {
        this.id = id;
        this.recipeId = recipeId;
        this.name = name;
        this.ingredients = ingredients;
        this.steps = steps;
        this.servings = servings;
        this.image = image;
    }

    public int getId() {
        return id;
    }

    public int getRecipeId() {
        return recipeId;
    }

    public String getName() {
        return name;
    }

    @TypeConverters(IngredientsConverter.class)
    public List<Ingredient> getIngredients() {
        return ingredients;
    }

    @TypeConverters(StepsConverter.class)
    public List<Step> getSteps() {
        return steps;
    }

    public int getServings() {
        return servings;
    }

    public String getImage() {
        return image;
    }
}
